title:              Science of Me
email:              vivannyati@gmail.com
description:        A website dedicated to Science of Me
author:             Start Bootstrap
baseurl:            ""
url:                "https://VivanNyati.github.io"

# Social Profiles
linkedin_username: vivan-nyati-8269b4313

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
